### ISSUE TITLE
Table fixed headers and scrollable body

### ISSUE THREAD

**Issue by AgisKounelis** [jemimaabu/dead-and-wounded#22]
Headers are scrollable as the body. It would be better if headers were always visible while scrolling

**Comment by bindiyah** [comment]
I have worked on this issue. Have a look on this.

**Comment by bindiyah** [comment]
Almost done, will be back very soon with the pull request.

**Comment by jemimaabu** [comment]
Hi @bindiyah, I've reviewed your pull request

**Comment by bindiyah** [comment]
The issue is resolved and updated.
