### ISSUE TITLE
Make Result Table Responsive

### ISSUE THREAD

**Issue by jemimaabu** [jemimaabu/dead-and-wounded#24]
**Problem**: The table displaying results is too wide on mobile

**Solution**: Create a media query styling rule with max-width: 992px for the table

**Comment by korayoksuztepe** [comment]
table-wrapper's width seems 700px.
Changing it's width to 100% and set max-width as 700px will fix the issue.
If you allow me, I want to do it as my first contribution.
Thanks

**Comment by jemimaabu** [comment]
Sure thing!
