### ISSUE TITLE
Create CSS File

### ISSUE THREAD

**Issue by jemimaabu** [jemimaabu/dead-and-wounded#4]
**Problem**: The repo currently doesn't have a CSS file

**Solution**: Create a main.css file and link the html file to it

**Comment by puranik9** [comment]
I can take this too. Would you like me to style the page a little bit?

**Comment by jemimaabu** [comment]
> I can take this too. Would you like me to style the page a little bit?

Yeah, sure thing!

**Comment by jemimaabu** [comment]
Hi @puranik9 , this issue has been resolved by someone so feel free to choose another. Thanks!
