### ISSUE TITLE
Include 'How To Play' div

### ISSUE THREAD

**Issue by jemimaabu** [jemimaabu/dead-and-wounded#5]
**Problem**: The page doesn't include instructions on how to play

**Solution**: Create an "instructions" div with the "How to Play" content detailed in [README.md](https://github.com/jemimaabu/dead-and-wounded/blob/master/README.md)

**Implementation**: Place the div above the form.

**Comment by puranik9** [comment]
I can take this and have a PR ready very soon

**Comment by jemimaabu** [comment]
> I can take this and have a PR ready very soon

Sounds good
