### ISSUE TITLE
Style the form error div

### ISSUE THREAD

**Issue by jemimaabu** [jemimaabu/dead-and-wounded#9]
**Implementation**: Apply a styling property to the form-errors div. Try to think of how errors in forms usually look and work with that.

**Additional context**
For bonus points:
- Highlight the input when an error occurs
- Make the form error transition (slideIn, fadeIN e.t.c.) into the page rather than just appearing

**Comment by Smollet777** [comment]
May i take it?

**Comment by jemimaabu** [comment]
Sure thing!
